#!/usr/bin/env python3
"""Seed ~40 biblical timeline events for study API."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.database import Base, SessionLocal, engine
from app.models.study import TimelineEvent

# --------------------------------------------------------------------------- #
# ~40 biblical timeline events (pt-BR) covering the full biblical narrative
# --------------------------------------------------------------------------- #
SEED = [
    # ── Primordios ──────────────────────────────────────────────────────────
    {
        "event_name": "Criacao",
        "description": "Deus cria os ceus, a terra e toda forma de vida, culminando na criacao do homem e da mulher.",
        "approximate_date": "~4000 AC",
        "date_start": -4000,
        "date_end": -4000,
        "event_type": "creation",
        "related_books": [1],
        "related_verses": [["1", "1", "1"], ["1", "1", "27"]],
    },
    {
        "event_name": "Queda",
        "description": "Adao e Eva desobedecem a Deus ao comer do fruto proibido, trazendo o pecado ao mundo.",
        "approximate_date": "~4000 AC",
        "date_start": -4000,
        "date_end": -4000,
        "event_type": "fall",
        "related_books": [1],
        "related_verses": [["1", "3", "6"], ["1", "3", "23"]],
    },
    {
        "event_name": "Diluvio",
        "description": "Deus envia um grande diluvio sobre a terra; Noe e sua familia sao salvos na arca.",
        "approximate_date": "~2348 AC",
        "date_start": -2348,
        "date_end": -2348,
        "event_type": "judgment",
        "related_books": [1],
        "related_verses": [["1", "6", "17"], ["1", "7", "11"]],
    },
    {
        "event_name": "Torre de Babel",
        "description": "A humanidade tenta construir uma torre ate o ceu; Deus confunde as linguas e dispersa os povos.",
        "approximate_date": "~2200 AC",
        "date_start": -2200,
        "date_end": -2200,
        "event_type": "judgment",
        "related_books": [1],
        "related_verses": [["1", "11", "1"], ["1", "11", "9"]],
    },
    # ── Patriarcas ──────────────────────────────────────────────────────────
    {
        "event_name": "Chamado de Abraao",
        "description": "Deus chama Abrao para deixar sua terra e ir para Canaa, prometendo-lhe uma grande nacao.",
        "approximate_date": "~2091 AC",
        "date_start": -2091,
        "date_end": -2091,
        "event_type": "covenant",
        "related_books": [1],
        "related_verses": [["1", "12", "1"], ["1", "12", "3"]],
    },
    {
        "event_name": "Nascimento de Isaque",
        "description": "Nasce Isaque, filho da promessa de Abraao e Sara, cumprindo a alianca de Deus.",
        "approximate_date": "~2066 AC",
        "date_start": -2066,
        "date_end": -2066,
        "event_type": "birth",
        "related_books": [1],
        "related_verses": [["1", "21", "1"], ["1", "21", "3"]],
    },
    {
        "event_name": "Jaco e Israel",
        "description": "Jaco luta com Deus e recebe o nome Israel; seus 12 filhos originarao as tribos de Israel.",
        "approximate_date": "~1900 AC",
        "date_start": -1900,
        "date_end": -1900,
        "event_type": "covenant",
        "related_books": [1],
        "related_verses": [["1", "32", "28"], ["1", "35", "10"]],
    },
    {
        "event_name": "Jose no Egito",
        "description": "Jose e vendido pelos irmaos e levado ao Egito, onde se torna governador e salva sua familia da fome.",
        "approximate_date": "~1898 AC",
        "date_start": -1898,
        "date_end": -1805,
        "event_type": "migration",
        "related_books": [1],
        "related_verses": [["1", "37", "28"], ["1", "41", "41"]],
    },
    # ── Egito e Exodo ───────────────────────────────────────────────────────
    {
        "event_name": "Escravidao no Egito",
        "description": "Os descendentes de Israel se multiplicam no Egito e sao escravizados pelos faraos.",
        "approximate_date": "~1800-1446 AC",
        "date_start": -1800,
        "date_end": -1446,
        "event_type": "oppression",
        "related_books": [1, 2],
        "related_verses": [["2", "1", "8"], ["2", "1", "14"]],
    },
    {
        "event_name": "Nascimento de Moises",
        "description": "Moises nasce no Egito e e salvo das aguas por uma princesa egipcia.",
        "approximate_date": "~1526 AC",
        "date_start": -1526,
        "date_end": -1526,
        "event_type": "birth",
        "related_books": [2],
        "related_verses": [["2", "2", "1"], ["2", "2", "10"]],
    },
    {
        "event_name": "Exodo",
        "description": "Deus liberta Israel da escravidao no Egito por meio de Moises, com grandes sinais e maravilhas.",
        "approximate_date": "~1446 AC",
        "date_start": -1446,
        "date_end": -1446,
        "event_type": "exodus",
        "related_books": [2],
        "related_verses": [["2", "12", "31"], ["2", "14", "21"]],
    },
    {
        "event_name": "Monte Sinai e a Lei",
        "description": "Deus entrega os Dez Mandamentos e a Lei a Moises no Monte Sinai.",
        "approximate_date": "~1446 AC",
        "date_start": -1446,
        "date_end": -1446,
        "event_type": "covenant",
        "related_books": [2],
        "related_verses": [["2", "19", "20"], ["2", "20", "1"]],
    },
    {
        "event_name": "40 Anos no Deserto",
        "description": "Israel vaga pelo deserto durante 40 anos devido a incredulidade do povo.",
        "approximate_date": "~1446-1406 AC",
        "date_start": -1446,
        "date_end": -1406,
        "event_type": "wandering",
        "related_books": [4, 5],
        "related_verses": [["4", "14", "33"], ["5", "8", "2"]],
    },
    # ── Terra Prometida ─────────────────────────────────────────────────────
    {
        "event_name": "Conquista de Canaa",
        "description": "Josue lidera Israel na conquista da terra prometida de Canaa.",
        "approximate_date": "~1406-1375 AC",
        "date_start": -1406,
        "date_end": -1375,
        "event_type": "conquest",
        "related_books": [6],
        "related_verses": [["6", "1", "1"], ["6", "6", "20"]],
    },
    {
        "event_name": "Periodo dos Juizes",
        "description": "Israel passa por ciclos de pecado, opressao, arrependimento e libertacao sob os juizes.",
        "approximate_date": "~1375-1050 AC",
        "date_start": -1375,
        "date_end": -1050,
        "event_type": "era",
        "related_books": [7, 8],
        "related_verses": [["7", "2", "16"], ["7", "21", "25"]],
    },
    {
        "event_name": "Historia de Rute",
        "description": "Rute, uma moabita, demonstra fidelidade a sua sogra Noemi e se torna antepassada de Davi.",
        "approximate_date": "~1100 AC",
        "date_start": -1100,
        "date_end": -1100,
        "event_type": "narrative",
        "related_books": [8],
        "related_verses": [["8", "1", "16"], ["8", "4", "17"]],
    },
    # ── Monarquia ───────────────────────────────────────────────────────────
    {
        "event_name": "Samuel – Ultimo Juiz e Profeta",
        "description": "Samuel serve como ultimo juiz de Israel e unge os dois primeiros reis.",
        "approximate_date": "~1070-1010 AC",
        "date_start": -1070,
        "date_end": -1010,
        "event_type": "era",
        "related_books": [9],
        "related_verses": [["9", "3", "20"], ["9", "7", "15"]],
    },
    {
        "event_name": "Reinado de Saul",
        "description": "Saul e ungido como o primeiro rei de Israel, mas desobedece a Deus e perde o trono.",
        "approximate_date": "~1050-1010 AC",
        "date_start": -1050,
        "date_end": -1010,
        "event_type": "reign",
        "related_books": [9],
        "related_verses": [["9", "10", "1"], ["9", "31", "4"]],
    },
    {
        "event_name": "Reinado de Davi",
        "description": "Davi, o pastor que venceu Golias, torna-se rei e estabelece Jerusalem como capital.",
        "approximate_date": "~1010-970 AC",
        "date_start": -1010,
        "date_end": -970,
        "event_type": "reign",
        "related_books": [9, 10],
        "related_verses": [["10", "5", "4"], ["10", "7", "16"]],
    },
    {
        "event_name": "Construcao do Templo de Salomao",
        "description": "Salomao constroi o primeiro Templo de Jerusalem, cumprindo o desejo de Davi.",
        "approximate_date": "~966-959 AC",
        "date_start": -966,
        "date_end": -959,
        "event_type": "construction",
        "related_books": [11],
        "related_verses": [["11", "6", "1"], ["11", "8", "10"]],
    },
    {
        "event_name": "Divisao do Reino",
        "description": "Apos a morte de Salomao, Israel se divide em Reino do Norte (Israel) e Reino do Sul (Juda).",
        "approximate_date": "~930 AC",
        "date_start": -930,
        "date_end": -930,
        "event_type": "division",
        "related_books": [11],
        "related_verses": [["11", "12", "16"], ["11", "12", "20"]],
    },
    # ── Profetas e Queda ────────────────────────────────────────────────────
    {
        "event_name": "Profetas do Norte – Elias",
        "description": "O profeta Elias confronta a idolatria no Reino do Norte e desafia os profetas de Baal.",
        "approximate_date": "~870-850 AC",
        "date_start": -870,
        "date_end": -850,
        "event_type": "prophecy",
        "related_books": [11],
        "related_verses": [["11", "18", "21"], ["11", "18", "38"]],
    },
    {
        "event_name": "Profetas do Norte – Eliseu",
        "description": "Eliseu sucede Elias e realiza diversos milagres em Israel.",
        "approximate_date": "~850-800 AC",
        "date_start": -850,
        "date_end": -800,
        "event_type": "prophecy",
        "related_books": [12],
        "related_verses": [["12", "2", "9"], ["12", "2", "14"]],
    },
    {
        "event_name": "Queda de Israel (Assiria)",
        "description": "O Reino do Norte (Israel) e conquistado pela Assiria; as dez tribos sao dispersas.",
        "approximate_date": "722 AC",
        "date_start": -722,
        "date_end": -722,
        "event_type": "judgment",
        "related_books": [12],
        "related_verses": [["12", "17", "6"], ["12", "17", "23"]],
    },
    {
        "event_name": "Queda de Juda (Babilonia)",
        "description": "Nabucodonosor conquista Jerusalem, destroi o Templo e leva Juda ao exilio.",
        "approximate_date": "586 AC",
        "date_start": -586,
        "date_end": -586,
        "event_type": "judgment",
        "related_books": [12],
        "related_verses": [["12", "25", "8"], ["12", "25", "11"]],
    },
    {
        "event_name": "Exilio na Babilonia",
        "description": "O povo de Juda permanece cativo na Babilonia por cerca de 70 anos, conforme profetizado.",
        "approximate_date": "586-516 AC",
        "date_start": -586,
        "date_end": -516,
        "event_type": "exile",
        "related_books": [27],
        "related_verses": [["27", "1", "1"], ["27", "9", "2"]],
    },
    {
        "event_name": "Daniel na Babilonia",
        "description": "Daniel serve fielmente a Deus no exilio, interpreta sonhos e sobrevive a cova dos leoes.",
        "approximate_date": "~605-536 AC",
        "date_start": -605,
        "date_end": -536,
        "event_type": "narrative",
        "related_books": [27],
        "related_verses": [["27", "6", "22"], ["27", "2", "28"]],
    },
    # ── Retorno e Reconstrucao ──────────────────────────────────────────────
    {
        "event_name": "Retorno do Exilio",
        "description": "Ciro, rei da Persia, permite que os judeus retornem a Jerusalem.",
        "approximate_date": "538 AC",
        "date_start": -538,
        "date_end": -538,
        "event_type": "restoration",
        "related_books": [15],
        "related_verses": [["15", "1", "1"], ["15", "1", "3"]],
    },
    {
        "event_name": "Reconstrucao do Templo",
        "description": "Os judeus que retornaram reconstroem o Templo de Jerusalem (segundo Templo).",
        "approximate_date": "~520-516 AC",
        "date_start": -520,
        "date_end": -516,
        "event_type": "construction",
        "related_books": [15],
        "related_verses": [["15", "3", "10"], ["15", "6", "15"]],
    },
    {
        "event_name": "Esdras e a Reforma",
        "description": "Esdras, sacerdote e escriba, lidera uma reforma espiritual e ensina a Lei ao povo.",
        "approximate_date": "~458 AC",
        "date_start": -458,
        "date_end": -458,
        "event_type": "reform",
        "related_books": [15],
        "related_verses": [["15", "7", "10"], ["15", "10", "1"]],
    },
    {
        "event_name": "Neemias e a Reconstrucao dos Muros",
        "description": "Neemias lidera a reconstrucao dos muros de Jerusalem em apenas 52 dias.",
        "approximate_date": "~445 AC",
        "date_start": -445,
        "date_end": -445,
        "event_type": "construction",
        "related_books": [16],
        "related_verses": [["16", "2", "17"], ["16", "6", "15"]],
    },
    {
        "event_name": "Historia de Ester",
        "description": "Ester, rainha judia na Persia, salva seu povo de um plano de exterminio.",
        "approximate_date": "~473 AC",
        "date_start": -473,
        "date_end": -473,
        "event_type": "narrative",
        "related_books": [17],
        "related_verses": [["17", "4", "14"], ["17", "8", "11"]],
    },
    {
        "event_name": "Periodo Intertestamentario",
        "description": "Cerca de 400 anos de silencio profetico entre o Antigo e o Novo Testamento.",
        "approximate_date": "~430-5 AC",
        "date_start": -430,
        "date_end": -5,
        "event_type": "era",
        "related_books": [],
        "related_verses": None,
    },
    # ── Novo Testamento ─────────────────────────────────────────────────────
    {
        "event_name": "Nascimento de Joao Batista",
        "description": "Nasce Joao Batista, o precursor do Messias, filho de Zacarias e Isabel.",
        "approximate_date": "~5 AC",
        "date_start": -5,
        "date_end": -5,
        "event_type": "birth",
        "related_books": [42],
        "related_verses": [["42", "1", "57"], ["42", "1", "80"]],
    },
    {
        "event_name": "Nascimento de Jesus",
        "description": "Jesus Cristo nasce em Belem, conforme as profecias messianicas.",
        "approximate_date": "~4 AC",
        "date_start": -4,
        "date_end": -4,
        "event_type": "birth",
        "related_books": [40, 42],
        "related_verses": [["40", "2", "1"], ["42", "2", "7"]],
    },
    {
        "event_name": "Batismo de Jesus",
        "description": "Jesus e batizado por Joao Batista no rio Jordao; o Espirito Santo desce sobre Ele.",
        "approximate_date": "~27 DC",
        "date_start": 27,
        "date_end": 27,
        "event_type": "ministry",
        "related_books": [40, 41, 42],
        "related_verses": [["40", "3", "16"], ["41", "1", "9"]],
    },
    {
        "event_name": "Ministerio de Jesus",
        "description": "Jesus prega o evangelho do Reino, cura enfermos e faz discipulos por cerca de tres anos.",
        "approximate_date": "~27-30 DC",
        "date_start": 27,
        "date_end": 30,
        "event_type": "ministry",
        "related_books": [40, 41, 42, 43],
        "related_verses": [["40", "4", "23"], ["43", "3", "16"]],
    },
    {
        "event_name": "Ultima Ceia",
        "description": "Jesus celebra a ultima refeicao com seus discipulos e institui a Santa Ceia.",
        "approximate_date": "~30 DC",
        "date_start": 30,
        "date_end": 30,
        "event_type": "ministry",
        "related_books": [40, 41, 42, 43],
        "related_verses": [["40", "26", "26"], ["42", "22", "19"]],
    },
    {
        "event_name": "Crucificacao de Jesus",
        "description": "Jesus e crucificado no Calvario, dando Sua vida como sacrificio pelos pecados da humanidade.",
        "approximate_date": "~30 DC",
        "date_start": 30,
        "date_end": 30,
        "event_type": "death",
        "related_books": [40, 41, 42, 43],
        "related_verses": [["40", "27", "35"], ["43", "19", "30"]],
    },
    {
        "event_name": "Ressurreicao de Jesus",
        "description": "Jesus ressuscita dos mortos ao terceiro dia, vencendo a morte e o pecado.",
        "approximate_date": "~30 DC",
        "date_start": 30,
        "date_end": 30,
        "event_type": "resurrection",
        "related_books": [40, 41, 42, 43],
        "related_verses": [["40", "28", "6"], ["43", "20", "16"]],
    },
    {
        "event_name": "Ascensao de Jesus",
        "description": "Jesus sobe ao ceu diante de seus discipulos e promete o envio do Espirito Santo.",
        "approximate_date": "~30 DC",
        "date_start": 30,
        "date_end": 30,
        "event_type": "ascension",
        "related_books": [42, 44],
        "related_verses": [["42", "24", "51"], ["44", "1", "9"]],
    },
    {
        "event_name": "Pentecostes",
        "description": "O Espirito Santo desce sobre os discipulos em Jerusalem, marcando o inicio da Igreja.",
        "approximate_date": "~30 DC",
        "date_start": 30,
        "date_end": 30,
        "event_type": "holy_spirit",
        "related_books": [44],
        "related_verses": [["44", "2", "1"], ["44", "2", "4"]],
    },
    {
        "event_name": "Conversao de Paulo",
        "description": "Saulo de Tarso encontra o Cristo ressurreto no caminho de Damasco e se converte.",
        "approximate_date": "~34 DC",
        "date_start": 34,
        "date_end": 34,
        "event_type": "conversion",
        "related_books": [44],
        "related_verses": [["44", "9", "3"], ["44", "9", "15"]],
    },
    {
        "event_name": "Viagens Missionarias de Paulo",
        "description": "Paulo realiza viagens missionarias pelo Imperio Romano, plantando igrejas e pregando o evangelho.",
        "approximate_date": "~46-62 DC",
        "date_start": 46,
        "date_end": 62,
        "event_type": "mission",
        "related_books": [44],
        "related_verses": [["44", "13", "2"], ["44", "28", "31"]],
    },
    {
        "event_name": "Destruicao de Jerusalem",
        "description": "O exercito romano sob Tito destroi Jerusalem e o segundo Templo, conforme Jesus profetizou.",
        "approximate_date": "70 DC",
        "date_start": 70,
        "date_end": 70,
        "event_type": "judgment",
        "related_books": [40, 41, 42],
        "related_verses": [["40", "24", "1"], ["42", "21", "20"]],
    },
]


def main():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        inserted = 0
        skipped = 0
        for row in SEED:
            # Dedup: skip if event_name already exists
            exists = (
                db.query(TimelineEvent)
                .filter(TimelineEvent.event_name == row["event_name"])
                .first()
            )
            if exists:
                skipped += 1
                continue
            db.add(TimelineEvent(**row))
            inserted += 1
        db.commit()
        print(f"Inserted {inserted} timeline events ({skipped} already existed).")
    finally:
        db.close()


if __name__ == "__main__":
    main()
